# -*- coding: utf-8 -*-
"""Post-covid-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZNmHMx1zPgg-hKoTLShSl_RVV6WNZgHE
"""

import numpy as np
import pandas as pd

# Load hospital beds dataset
df_pre_covid = pd.read_csv("pre_covid_occupancy.csv")

# Get unique states and total beds
df_beds = df_pre_covid[['state', 'total_beds']].drop_duplicates()

# Date range for post-COVID (2020–2021)
date_range = pd.date_range(start='2020-01-01', end='2021-12-01', freq='MS')

# Simulate post-COVID occupancy
rows = []
np.random.seed(42)

for _, row in df_beds.iterrows():
    state = row['state']
    total_beds = row['total_beds']
    for date in date_range:
        # Pandemic shock: simulate peaks in 2020
        if date.month in [4, 5, 6, 9, 10, 11]:  # Pandemic wave months
            occupancy_rate = np.random.uniform(1.0, 1.2)  # Overcapacity
        else:
            occupancy_rate = np.random.uniform(0.6, 0.75)  # Normal-ish

        occupancy_rate = min(max(occupancy_rate, 0), 1.2)  # Clamp to 120%
        occupied_beds = int(total_beds * min(occupancy_rate, 1.0))  # Beds can't go beyond capacity

        rows.append([state, date, total_beds, occupied_beds, occupancy_rate])

# Create DataFrame
df_post_covid = pd.DataFrame(rows, columns=['state', 'date', 'total_beds', 'occupied_beds', 'occupancy_rate'])

# Save to CSV
df_post_covid.to_csv("post_covid_occupancy.csv", index=False)
print(" Post-COVID occupancy data saved as 'post_covid_occupancy.csv'")